# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.0
_src_path: gh:mjun0812/python-copier-template
author_email: y.nakayama.penticton00@gmail.com
author_name: Yusuke Nakayama
description: Prompt Tuning
package_name: prompt_tuning
project_name: prompt_tuning
python_version: '3.12'
